name: Upload to S3

on:
  schedule:
    - cron: '0 0 * * SUN'
    #- cron: '15 * * * *'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: shallwefootball/s3-upload-action@master
        with:
          endpoint: "https://obs.cn-east-3.myhuaweicloud.com"
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: '.'
